name: C/C++ CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Create bin directory
      run: mkdir ${{github.workspace}}/build
    - name: make
      run: make
